// ============================================================
//  AutoElite — Base de dados de veículos
// ============================================================

const VEICULOS = [
  {
    id: 1,
    nome: "BMW Série 3 330i",
    marca: "BMW",
    tipo: "Sedan",
    ano: 2024,
    km: 12000,
    preco: 289900,
    combustivel: "Gasolina",
    cambio: "Automático",
    cor: "Preto",
    potencia: "258 cv",
    destaque: true,
    novo: false,
    imagem: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
    descricao: "Desempenho esportivo aliado ao requinte alemão. Motor TwinPower Turbo, painel digital e sistema iDrive de última geração.",
    caracteristicas: ["Teto solar panorâmico", "Bancos em couro", "Câmera 360°", "Carregamento wireless", "Head-up display"]
  },
  {
    id: 2,
    nome: "Mercedes-Benz GLC 300",
    marca: "Mercedes-Benz",
    tipo: "SUV",
    ano: 2024,
    km: 8500,
    preco: 389900,
    combustivel: "Gasolina",
    cambio: "Automático",
    cor: "Prata",
    potencia: "258 cv",
    destaque: true,
    novo: false,
    imagem: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    descricao: "Sofisticação e tecnologia em cada detalhe. Interior luxuoso com MBUX e assistência ativa ao condutor.",
    caracteristicas: ["MBUX com IA", "Suspensão air body", "Ambient light 64 cores", "Piloto automático adaptativo", "Teto panorâmico"]
  },
  {
    id: 3,
    nome: "Porsche Cayenne",
    marca: "Porsche",
    tipo: "SUV",
    ano: 2023,
    km: 21000,
    preco: 529900,
    combustivel: "Gasolina",
    cambio: "Automático",
    cor: "Branco",
    potencia: "340 cv",
    destaque: false,
    novo: false,
    imagem: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    descricao: "O SUV esportivo por excelência. DNA Porsche com conforto para o dia a dia e emoção para a estrada.",
    caracteristicas: ["PASM adaptativo", "Banco 18 vias", "PCM com GPS", "Bose Surround Sound", "Modo Sport Plus"]
  },
  {
    id: 4,
    nome: "Audi A5 Sportback",
    marca: "Audi",
    tipo: "Hatch",
    ano: 2024,
    km: 5200,
    preco: 319900,
    combustivel: "Gasolina",
    cambio: "Automático",
    cor: "Cinza",
    potencia: "249 cv",
    destaque: false,
    novo: true,
    imagem: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
    descricao: "Design progressivo e quattro permanente. Virtual Cockpit Plus e matrix LED para uma condução incomparável.",
    caracteristicas: ["Quattro all-wheel drive", "Virtual Cockpit Plus", "Matrix LED", "Bang & Olufsen", "Drive Select"]
  },
  {
    id: 5,
    nome: "Toyota Corolla Cross GR",
    marca: "Toyota",
    tipo: "SUV",
    ano: 2024,
    km: 3000,
    preco: 179900,
    combustivel: "Híbrido",
    cambio: "CVT",
    cor: "Vermelho",
    potencia: "122 cv",
    destaque: false,
    novo: true,
    imagem: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
    descricao: "Híbrido com estilo esportivo GR. Economia sem abrir mão do prazer de dirigir.",
    caracteristicas: ["Motor híbrido", "Toyota Safety Sense", "Central 10.1\"", "Câmera traseira", "Controle de tração"]
  },
  {
    id: 6,
    nome: "Volvo XC60 B5",
    marca: "Volvo",
    tipo: "SUV",
    ano: 2023,
    km: 18000,
    preco: 409900,
    combustivel: "Híbrido",
    cambio: "Automático",
    cor: "Azul",
    potencia: "250 cv",
    destaque: true,
    novo: false,
    imagem: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80",
    descricao: "Segurança escandinava com design minimalista. Mild hybrid com tração integral inteligente.",
    caracteristicas: ["Pilot Assist", "Harman Kardon 600W", "Air cleaner", "360° câmera", "Google nativo"]
  },
  {
    id: 7,
    nome: "Honda Civic Type R",
    marca: "Honda",
    tipo: "Hatch",
    ano: 2024,
    km: 1200,
    preco: 299900,
    combustivel: "Gasolina",
    cambio: "Manual",
    cor: "Vermelho",
    potencia: "330 cv",
    destaque: false,
    novo: true,
    imagem: "https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800&q=80",
    descricao: "O hatch mais rápido de Nürburgring. Aerodinâmica ativa, bancos Alcantara e tração dianteira visceral.",
    caracteristicas: ["Banco Alcantara", "Brembo 6 pistões", "Rev match", "Log mode", "Aerodinâmica ativa"]
  },
  {
    id: 8,
    nome: "Range Rover Velar",
    marca: "Land Rover",
    tipo: "SUV",
    ano: 2023,
    km: 27000,
    preco: 469900,
    combustivel: "Gasolina",
    cambio: "Automático",
    cor: "Preto",
    potencia: "296 cv",
    destaque: false,
    novo: false,
    imagem: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&q=80",
    descricao: "Elegância britânica sobre qualquer terreno. Interface Touch Pro Duo e suspensão pneumática adaptativa.",
    caracteristicas: ["Touch Pro Duo", "Suspensão pneumática", "All Terrain Progress", "Meridian 3D Audio", "Gesture tailgate"]
  },
  {
    id: 9,
    nome: "Chevrolet Camaro SS",
    marca: "Chevrolet",
    tipo: "Esportivo",
    ano: 2023,
    km: 9800,
    preco: 379900,
    combustivel: "Gasolina",
    cambio: "Manual",
    cor: "Amarelo",
    potencia: "455 cv",
    destaque: false,
    novo: false,
    imagem: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    descricao: "V8 6.2L que ecoa na alma. Muscle car americano puro com tecnologia moderna e presença de pista.",
    caracteristicas: ["V8 6.2L LS3", "Brembo 4 pistões", "Magnetorheological suspension", "Bose 9 alto-falantes", "Launch control"]
  },
  {
    id: 10,
    nome: "Tesla Model 3 LR",
    marca: "Tesla",
    tipo: "Sedan",
    ano: 2024,
    km: 6700,
    preco: 319900,
    combustivel: "Elétrico",
    cambio: "Automático",
    cor: "Branco",
    potencia: "498 cv",
    destaque: true,
    novo: false,
    imagem: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80",
    descricao: "Autopilot, 629 km de autonomia e aceleração de 3.1s até 100 km/h. O futuro chegou.",
    caracteristicas: ["Autopilot", "629 km autonomia", "Tela 15.4\"", "OTA updates", "Supercharger V3"]
  },
  {
    id: 11,
    nome: "Jeep Wrangler Rubicon",
    marca: "Jeep",
    tipo: "SUV",
    ano: 2024,
    km: 4400,
    preco: 389900,
    combustivel: "Gasolina",
    cambio: "Automático",
    cor: "Verde",
    potencia: "272 cv",
    destaque: false,
    novo: true,
    imagem: "https://images.unsplash.com/photo-1551830820-330a71b99659?w=800&q=80",
    descricao: "Lenda off-road com tecnologia moderna. Rock-Trac 4x4 e diferencial Dana 44 para qualquer aventura.",
    caracteristicas: ["Rock-Trac 4WD", "Dana 44 dif.", "Teto removível", "Câmera frontal off-road", "E-Locker traseiro"]
  },
  {
    id: 12,
    nome: "Porsche 911 Carrera S",
    marca: "Porsche",
    tipo: "Esportivo",
    ano: 2024,
    km: 2100,
    preco: 849900,
    combustivel: "Gasolina",
    cambio: "Automático",
    cor: "Prata",
    potencia: "450 cv",
    destaque: true,
    novo: true,
    imagem: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800&q=80",
    descricao: "O esportivo de referência há 60 anos. Boxer 3.0T biturbo, PDK 8 marchas e identidade inconfundível.",
    caracteristicas: ["PDK 8 velocidades", "PASM+", "Sport Chrono", "Burmester High-End", "Rear axle steering"]
  }
];

const MARCAS = [...new Set(VEICULOS.map(v => v.marca))].sort();
const TIPOS = [...new Set(VEICULOS.map(v => v.tipo))].sort();
const COMBUSTIVEIS = [...new Set(VEICULOS.map(v => v.combustivel))].sort();